### PR TITLE
Multishot overhaul

### PR DESCRIPTION
**Pull request by OffsetMonkey538**
Some ideas from #3 

- [x] Multishot works on multiple items
	- [x] Bows
	- [x] Throwable items
		- [x] Snowballs
		- [x] Eggs
		- [x] Potions
		- [x] Ender Pearls
		- [x] Experience Bottles
- [x] Rename mod to "Better Multishot"
- [x] Refactoring
- [x] Change mod description

### CODE REVIEW

**Comment by OffsetMonkey538** [comment]
I know that `@Overwrite`ing something is not a very good idea but I think because of how the code works I need to do that

**Comment by OffsetMonkey538** [comment]
Currently replacing bow code with crossbow code. If I get it to work, then the bow would just be a crossbow but without the ability of shooting fireworks and with the ability to have bow enchantments.I thought it might be a good idea to make bows only be able to use level 1 of multishot so they don't become so op and there is still reason to use a crossbow

**Comment by OffsetMonkey538** [comment]
Ok so there's a problem. Making bows limited to level 1 of multishot won't work very good.
The new idea is to make the arrows from multishot do half the damage of a normal arrow.

**Comment by OffsetMonkey538** [comment]
I would say that bows are now done, if there are problems, please tell me.

**Comment by HyperSoop** [comment]
You could make a setting to not nerf bow multishot arrows / not cap multishot on bows - it's also a cursed mod, after all

**Comment by OffsetMonkey538** [comment]
alright

**Comment by OffsetMonkey538** [comment]
And with that, the bug that made it impossible to get the multishot enchantment on a bow using an enchanting table has been squashed

**Comment by OffsetMonkey538** [comment]
Seems like I need to make the throwable items be enchanted using an anvil. Might be a good idea to do the same to the bow, that would save me from Fabric-ASM, the thing I spent like half the day to get working.

**Comment by OffsetMonkey538** [comment]
I got a better(?) idea, making crossbows shoot the throwable items, Not sure if it'd fit the theme of better multishot tho

**Comment by OffsetMonkey538** [comment]
Alright so it seems that because of the ``Too expensive`` thing that anvils do, it's only possible to enchant one throwable item at a time... I *think* it could be possible to use a mixin and change the anvil code to accept these items but I'll first get the enchant working and then work on that

**Comment by OffsetMonkey538** [comment]
Alright snowballs *should* work now

**Comment by OffsetMonkey538** [comment]
I would say that eggs are also done now

**Comment by HyperSoop** [comment]
ooo experience bottles
anyway, about enchanting, i think you could make an override than it's at most 40 levels to enchant it and deosn't go into too expensive, with a config boolean ofc

**Comment by OffsetMonkey538** [comment]
I haven't looked at the anvil code yet but my guess is that something about having multiple items makes it freak out because enchanting only one was like 4 levels or something. Also, it might be easier to chat on [discord](https://offsetmonkey538.github.io/links/discord)

**Pull request merged**
